# Generated by Django 3.2.7 on 2021-10-07 03:26

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('firstname', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='This is not a Valid name', regex='[a-z]')])),
                ('lastname', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='This is not a Valid name', regex='[a-z]')])),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone length is exactly 11, Prefix is with in allowed ones 010, 011, 012, 015', regex='^01[0125][0-9]{8}$')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('haveshop', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_information', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
